name: Rust CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Rust Linting and Formatting
        run: |
          cargo fmt 
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all-targets
      #- name: Run tests
      #  run: cargo test --all
      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: platform-cv
          path: target/release/